# Generated by Django 4.1.4 on 2022-12-23 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.CharField(max_length=50)),
                ("order", models.CharField(max_length=50)),
                ("orderPlaced", models.CharField(max_length=50)),
                ("orderTransit", models.CharField(max_length=50)),
                ("orderShipment", models.CharField(max_length=50)),
                ("outForDelivery", models.CharField(max_length=50)),
                ("delivered", models.CharField(max_length=50)),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
