# Generated by Django 4.1.4 on 2022-12-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trackapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="track", name="deliveredDate", field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="track",
            name="orderPlacedDate",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="track",
            name="orderShipmentDate",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="track",
            name="orderTransitDate",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="track",
            name="outForDeliveryDate",
            field=models.DateField(null=True),
        ),
    ]
