# Generated by Django 4.1.4 on 2022-12-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trackapp", "0003_alter_track_delivereddate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="track",
            name="order",
            field=models.CharField(default="false", max_length=50),
        ),
    ]
