# Generated by Django 4.1.4 on 2022-12-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trackapp", "0005_alter_track_delivered_alter_track_delivereddate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="track",
            name="bio",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="track",
            name="deliveredDate",
            field=models.CharField(default="___ __ ____", max_length=50),
        ),
        migrations.AlterField(
            model_name="track",
            name="orderPlacedDate",
            field=models.CharField(default="___ __ ____", max_length=50),
        ),
        migrations.AlterField(
            model_name="track",
            name="orderShipmentDate",
            field=models.CharField(default="___ __ ____", max_length=50),
        ),
        migrations.AlterField(
            model_name="track",
            name="orderTransitDate",
            field=models.CharField(default="___ __ ____", max_length=50),
        ),
        migrations.AlterField(
            model_name="track",
            name="outForDeliveryDate",
            field=models.CharField(default="___ __ ____", max_length=50),
        ),
    ]
