# Generated by Django 4.1.4 on 2022-12-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trackapp", "0006_alter_track_bio_alter_track_delivereddate_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="track", name="orderTransit",),
        migrations.RemoveField(model_name="track", name="orderTransitDate",),
        migrations.AddField(
            model_name="track",
            name="deliveredtime",
            field=models.CharField(default="00:00 AM", max_length=50),
        ),
        migrations.AddField(
            model_name="track",
            name="orderPlacedtime",
            field=models.CharField(default="00:00 AM", max_length=50),
        ),
        migrations.AddField(
            model_name="track",
            name="orderShipmentTime",
            field=models.CharField(default="00:00 AM", max_length=50),
        ),
        migrations.AddField(
            model_name="track",
            name="outForDeliveryTime",
            field=models.CharField(default="00:00 AM", max_length=50),
        ),
    ]
